service: play-lang-lambda

frameworkVersion: '3'

plugins:
  - serverless-bundle

custom:
  bundle:
    linting: false # TODO: enable and fix lint
    copyFiles:
      - from: './play-lang/parser'
        to: './play-lang/'

provider:
  name: aws
  runtime: nodejs14.x
  architecture: arm64
  stage: ${env:STAGE}
  region: ${env:AWS_REGION}

package:
  individually: true

functions:
  main:
    handler: index.handler
